### ISSUE TITLE
Pull request creation not working on aw submit

### ISSUE THREAD

**Issue by marcioj** [inaka/assisted_workflow#14]
```
~ aw submit
     pivotal  loading story #130986965
         git  preparing local branch
git checkout master
Switched to branch 'master'
git pull --rebase
git checkout marcioj.130986965.sign_up_design_modification___
Switched to branch 'marcioj.130986965.sign_up_design_modification___'
git rebase master
git push -u -f origin marcioj.130986965.sign_up_design_modification___
Counting objects: 14, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (14/14), 1.55 KiB | 0 bytes/s, done.
Total 14 (delta 9), reused 0 (delta 0)
remote: Resolving deltas: 100% (9/9), completed with 9 local objects.
To github.com:JovioGH/jovio_server.git
 * [new branch]      marcioj.130986965.sign_up_design_modification___ -> marcioj.130986965.sign_up_design_modification___
git config --get remote.origin.url
      github  submiting the new pull request
/home/marcio/.rvm/gems/ruby-2.3.1/gems/octokit-2.7.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/JovioGH/jovio_server/pulls: 404 - Not Found // See: https://developer.github.com/v3/pulls/#create-a-pull-request (Octokit::NotFound)
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/octokit-2.7.2/lib/octokit/client.rb:257:in `request'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/octokit-2.7.2/lib/octokit/client.rb:138:in `post'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/octokit-2.7.2/lib/octokit/client/pull_requests.rb:54:in `create_pull_request'
        from /home/marcio/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/assisted_workflow-0.4.0/lib/assisted_workflow/addons/github.rb:71:in `create_pull_request'
        from /home/marcio/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/assisted_workflow-0.4.0/lib/assisted_workflow/cli.rb:62:in `submit'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/marcio/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/assisted_workflow-0.4.0/lib/assisted_workflow/cli.rb:134:in `start'
        from /home/marcio/.rvm/gems/ruby-2.3.1/gems/assisted_workflow-0.4.0/bin/aw:12:in `<top (required)>'
        from /home/marcio/.rvm/gems/ruby-2.3.1/bin/aw:23:in `load'
        from /home/marcio/.rvm/gems/ruby-2.3.1/bin/aw:23:in `<main>'
        from /home/marcio/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/marcio/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by marcioj** [comment]
Looks like I was using the wrong permission. I'll create a PR in order to improve the docs about it
